---
title: "Script que chama as funções do índice governabilidade"
output: html_notebook
---

```{r}
rm(list = ls())
```


# Paleta de cor 

```{r}
paleta = list(azul_4i = "#4C94FF", 
              laranja_4i = "#C4314B") 
```

# Configurações do usuário

```{r}
#Coleta o nome de usuário
user <- Sys.getenv('USERNAME')
user_path <- paste0('C:/Users/', user, '/')


if(user == 'GabrielBelle') {
  git_path <- paste0(user_path,
                   'Documents/Trabalhos/git/alternative-data/')

  alt_path <- paste0(user_path, 
                     '4intelligence/IT Admin - Operacional/trabalho/dados_alternativos/')
  
  
}else if (user == 'LuizPauloTavaresGonç') {
 git_path <- paste0(user_path,
                   'Documents/GitHub/alternative-data/governabilidade/alternative-data/')

  alt_path <- paste0(user_path,
                     '4intelligence/IT Admin - Operacional/trabalho/dados_alternativos/')
}
```

# Packages 


```{r}

# Packages Utilizados 
# Puxando a função user.packages 
source(paste0(git_path,
              'governabilidade/user_packages.R'))

# Packages Utilizados 

packages <- c("tidyverse",  
              "ggside", 
              "lubridate",
              "RColorBrewer", 
              "scales")

# Instalando/Liberando 
library_packages(packages)
```
# Tema 4i - theme()

```{r}

thema = theme(legend.position = "bottom",
              ggside.panel.scale = 0.2,
        panel.background = element_rect(fill = "transparent"),
        #strip.text = element_text(face="bold", size=9),
        strip.background = element_rect(fill = "#f5f5f5"), 
                legend.background = element_blank(),
                axis.text.x = element_text(angle = 90, 
                                           hjust = 1, 
                                           size = 16),
                axis.text.y = element_text(size = 14), 
                strip.text.x = element_text(size = 14),
                strip.text.y = element_text(size = 17),
                axis.title.y = element_text(size = 11L),
                legend.text = element_text(color = "#0A2240", 
                                           size =  15),
                legend.key = element_rect(fill = "transparent",
                                      colour = "transparent"),
            legend.key.size = unit(0.1, 'cm'),
            legend.margin = margin(-0.2, unit = "cm"),
            rect = element_rect(fill = "transparent"),
            plot.title.position = "plot",
            plot.margin = ggplot2::margin(1,1,1,1, 
                                  unit = "lines"),
            plot.caption.position =  "plot",
            # plot.caption = element_markdown(color = "black",
            #                                 size = 12),
            plot.title = element_text(color = "black", 
                                      size = 18,
                                      face = 'bold',
                                      margin = ggplot2::margin(b = 6)),
            plot.subtitle = element_text(color = "#616060",
                                         size = 14, 
                                         margin = ggplot2::margin(b = 6)),
            panel.grid.major = element_line(color = "#e9e9e9"),
            panel.grid.minor = element_blank(),
            panel.grid.major.x = element_blank(),
            panel.grid  = element_blank(),
            axis.ticks = element_blank(),
            plot.background = element_rect(fill = "transparent", 
                                           colour = NA))+
  theme(strip.text.x = element_text(margin = margin(.1, 1, .1, 1, "cm")))
```


# Carrega o índices

```{r}
legislativo <- readxl::read_excel(
  paste0(alt_path, 'governabilidade/output/Data/historico/2024/marco_2024/',
         'indice_legis.xlsx')
) %>% 
  select(date, gov, indice_legislativo)

judiciario <- readxl::read_excel(
  paste0(alt_path, 'governabilidade/output/Data/historico/2024/marco_2024/',
         'indice_judiciario.xlsx')
) %>% 
  select(date, indice_judiciario)
  
popularidade <- readxl::read_excel(
  paste0(alt_path, 'governabilidade/output/Data/historico/2024/marco_2024/',
         'indice_pop.xlsx')
) %>% 
  select(date, indice_pop)


indice_gov <- legislativo %>% 
  full_join(judiciario) %>% 
  full_join(popularidade) %>% 
  rowwise() %>% 
  mutate(indice_governabilidade = sum(indice_legislativo,
                                      indice_judiciario,
                                      indice_pop)/3,
         across(where(is.numeric), ~round(.x,2))) %>% 
  ungroup() %>% 
  rename(Judiciario = indice_judiciario, 
         Legislativo = indice_legislativo,
         Popularidade = indice_pop,
         Governabilidade = indice_governabilidade) %>% 
  filter(date >= '2003-01-01')

getwd()

saveRDS(indice_gov, "indice_governabilidade_revisada.rds")

indice_gov <- indice_governabilidade

```

```{r}
# igov_geral <- indice_gov %>% 
#              dplyr::filter(gov == "Lula III") %>%
#              stats::na.omit() %>% 
#              rename("I-GOV" = "Governabilidade", 
#                     "Judiciário" = "Judiciario") %>% 
#              pivot_longer(cols = Legislativo:`I-GOV`) %>% 
#              dplyr::mutate(value = value*100) %>% 
#             mutate(index = ifelse(name != "I-GOV", "0", "1"))

# Plote IGOV 

# igov_plot = ggplot(igov_geral) +
#   aes(x = name, y = value, fill = index) +
#   geom_col()+
#   scale_fill_manual(values = c(`0` = paleta$azul_4i,
#                                `1` = "orange"))+
#   ylim(0,100)+
#   labs(y = "%", 
#        x = "", fill = "")+
#   geom_text(aes(label = round(value,2), 
#                 hjust = 0.5, 
#             vjust = 2.5), 
#             size = 3.0)+
#   xlim("I-GOV","Popularidade", "Judiciário", "Legislativo")+
#   theme(legend.position = "null", 
#         axis.text.x = element_text(size = 80))

# parse_theme_4i(list(igov_plot),
#               title = "Índice de Governabilidade (I-GOV)",
#               subtitle = "O I-GOV é composto por três dimensões: popularidade, judiciário e legislativo.",
#               new_theme = F, file_format = "png")
#   

# Comparação entre governos 
# Pegando os primeiros 6 meses de cada ano 

# igov_six <- indice_gov %>%
#             mutate(ano = lubridate::year(date), 
#                    mes = lubridate::month(date)) %>%
#             group_by(ano) %>%
#   filter(ano %in% c("2003", "2007", "2011",
#                               "2015", "2016", "2019",
#                               "2023")) %>% ungroup() %>%
#   filter(mes == 6) %>% arrange(desc(Governabilidade)) %>%
#   rename("I-GOV" = "Governabilidade",
#          "Judiciário" = "Judiciario") %>% 
#   pivot_longer(cols = Legislativo:`I-GOV`) %>% 
#   mutate(index = ifelse(gov == "Lula III", "atual", "anterior")) %>% 
#   mutate(value = value*100)

        

# Definir a ordem desejada
# ordem <- factor(c("Lula I", "Lula II", "Dilma I", "Dilma II", "Temer", "Bolsonaro", "Lula III"))
# 
# 
# six_plot = ggplot(igov_six) +
#    aes(x = factor(gov, levels = ordem), y = value, fill = index)+
#   geom_col() +
#   scale_fill_manual(
#     values = c(anterior = paleta$azul_4i,
#     atual = "orange")) +
#   geom_text(aes(label = round(value,2), 
#                 vjust = 2.0, 
#                 hjust = 0.5), 
#             size = 1.8)+
#   facet_wrap(vars(name))+
#   theme(legend.position = "none")+
#   labs(y = "%", x = "")
  


# parse_theme_4i(list(six_plot),
#               title = "I-GOV no mês de junho de cada governo",
#               subtitle = "Considerando junho do primeiro ano de cada governo",
#               new_theme = F, file_format = "png")
# 
# 
# six_plot_lateral = ggplot(igov_six) +
#    aes(x = factor(gov, levels = ordem), y = value, fill = index)+
#   geom_col() +
#   scale_fill_manual(
#     values = c(anterior = paleta$azul_4i,
#     atual = "orange")) +
#   geom_text(aes(label = round(value,2), 
#                 vjust = 2.0, 
#                 hjust = 0.5), 
#             size = 1.8)+
#   facet_wrap(vars(name), strip.position = "right")+
#   theme(legend.position = "none")+
#   labs(y = "%", x = "")
#           
# 
# parse_theme_4i(list(six_plot_lateral),
#               title = "I-GOV  - teste lateral",
#               subtitle = "Considerando junho do primeiro ano de cada governo",
#               new_theme = F, file_format = "png")
# 
# # Sem governabilidade geral 
# igov_six2 <- igov_six %>% 
#         filter(name != "I-GOV") %>% 
#   filter(gov != "Temer")
# 
# six_plot_lateral_sem_gov = ggplot(igov_six2) +
#    aes(x = factor(gov, levels = ordem), y = value, fill = index)+
#   geom_col() +
#   scale_fill_manual(
#     values = c(anterior = paleta$azul_4i,
#     atual = "orange")) +
#   geom_text(aes(label = round(value,2), 
#                 vjust = 2.0, 
#                 hjust = 0.5), 
#             size = 1.8)+
#   facet_wrap(vars(name),ncol = 1,
#              strip.position = "right")+
#   theme(legend.position = "none")+
#   labs(y = "%", x = "")
#           
# parse_theme_4i(list(six_plot_lateral_sem_gov),
#               title = "Composição do I-GOV",
#               subtitle = "Considerando o mês de junho do primeiro ano de cada governo",
#               new_theme = F, file_format = "png")


# 

# igov_six3 <- igov_six %>% 
#         filter(name == "I-GOV") %>%
#         filter(gov != "Temer")
# 
# 
# six_plot_lateral_sem_gov = ggplot(igov_six3) +
#    aes(x = factor(gov, levels = ordem), y = value, fill = index)+
#   geom_col() +
#   scale_fill_manual(
#     values = c(anterior = paleta$azul_4i,
#     atual = "orange")) +
#   geom_text(aes(label = round(value,2), 
#                 vjust = 2.0, 
#                 hjust = 0.5), 
#             size = 1.8)+
#   ylim(0,100)+
#   # facet_wrap(vars(name),ncol = 1,
#   #            strip.position = "right")+
#   theme(legend.position = "none")+
#   labs(y = "%", x = "")
# 
# parse_theme_4i(list(six_plot_lateral_sem_gov),
#               title = "I-GOV - Comparação entre os governos",
#               subtitle = "Considerando o mês de junho do primeiro ano de cada governo",
#               new_theme = F, file_format = "png")

```


```{r}
writexl::write_xlsx(indice_gov,
                     paste0(alt_path, 
                           'governabilidade/output/',
                           'indice_governabilidade_setembro.xlsx'))
```


```{r}

test <- indice_gov %>% 
  dplyr::group_by(gov) %>%
  tidyr::fill(Legislativo, .direction = "down") %>%
  tidyr::fill(Legislativo, .direction = "up") %>% 
  tidyr::fill(Judiciario, .direction = "down") %>% 
  tidyr::fill(Judiciario, .direction = "up") %>% 
  tidyr::fill(Popularidade, .direction = "down") %>%
  tidyr::fill(Popularidade, .direction = "up") %>%
  tidyr::fill(Governabilidade, .direction = "down") %>%
  tidyr::fill(Governabilidade, .direction = "up") %>%
  dplyr::ungroup()


getwd()
writexl::write_xlsx(test,
                     paste0(alt_path, 
                           'governabilidade/output/',
                           'indice_gov_mod.xlsx'))

```


```{r}

# indice_gov <- indice_governabilidade

indice_gov %>% 
  mutate(gov = factor(gov, c('Lula I', 'Lula II',
                             'Dilma I', 'Dilma II', 'Temer', 'Bolsonaro', 
                             'Lula III')),
         date = as.Date(date)) %>% 
  #filter(date<='2022-12-01') %>% 
  ggplot2::ggplot()+ 
  aes(x = date, y = Governabilidade)+
  geom_line(size = 1.0)+
  facet_grid(~ gov,  scale = 'free_x', space="free_x")+
  labs(
    y = "", 
    x = "", 
    caption = "Fonte: organização metodológica 4i"
    )+
    ylim(0,1)+
    scale_y_continuous(labels = percent_format(), 
                       limits = c(0,1))+
    scale_x_date(date_labels = "%Y-%m",
                 date_breaks = '1 year',
                 date_minor_breaks = '3 month',
                 expand = c(0.05,1))+ thema

ggplot2::ggsave(
  filename =  paste0(
    alt_path,
    "governabilidade/output/Plots/",
    "/plot_indice_geral.png"), 
  width = 15, 
  height = 7, 
  dpi = 300, 
  units = "in",
  device='png')
```


```{r}
indice_gov %>% 
  pivot_longer(-c(date, gov)) %>% 
  mutate(name = factor(name, 
                       levels = c('Legislativo', 'Judiciario',
                       'Popularidade', 'Governabilidade')),
         gov = factor(gov, c('Lula I', 'Lula II',
                             'Dilma I', 'Dilma II', 'Temer', 'Bolsonaro')),
         date = as.Date(date)) %>% 
  ggplot2::ggplot()+ 
  aes(x = date, y = value)+
  geom_line(size = 1.0)+
  facet_grid(name~gov,  scale = 'free_x', space="free_x")+
  labs(y = "", x = "")+
  theme(legend.position = "bottom", 
        legend.text = element_text(size = 25),
        axis.text.x = element_text(angle = 45, 
                                   hjust = 1, 
                                   size = 15),
        axis.text.y = element_text(size = 15), 
        strip.text.x = element_text(size = 15),
        strip.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 20L),
        axis.title.x = element_blank(), 
        legend.title = element_blank())+
        ylim(0,1)+
        scale_y_continuous(labels = percent_format(), 
                           limits = c(0,1))+
        scale_x_date(date_labels = "%Y-%m",
                     date_breaks = '1 year',
                     date_minor_breaks = '3 month',
                     expand = c(0.05,1))

ggplot2::ggsave(
  filename =  paste0(
    alt_path,
    "governabilidade/output/Plots/IndiceGeral/v7_atualizada",
    "/plot02_geral.png"), 
  width = 15, 
  height = 7, 
  dpi = 300, 
  units = "in",
  device='png')
```

