---
title: "Script que chama as funções do índice governabilidade"
output: html_notebook
---

```{r}
rm(list = ls())
```


# Paleta 

```{r}
paleta = list(azul_4i = "#4C94FF", 
              laranja_4i = "#C4314B") 
```

# Configurações do usuário

```{r}
#Coleta o nome de usuário
user <- Sys.getenv('USERNAME')
user_path <- paste0('C:/Users/', user, '/')


if(user == 'GabrielBelle') {
  git_path <- paste0(user_path,
                   'Documents/Trabalhos/git/alternative-data/')

  alt_path <- paste0(user_path, 
                     '4intelligence/IT Admin - Operacional/trabalho/dados_alternativos/')
  
  
}else if (user == 'LuizPauloTavaresGonç') {
 git_path <- paste0(user_path,
                   'Documents/GitHub/alternative-data/governabilidade/alternative-data/')

  alt_path <- paste0(user_path,
                     '4intelligence/IT Admin - Operacional/trabalho/dados_alternativos/')
}

```

# Packages 

```{r}
# Puxando a função user.packages 

source(paste0(git_path,
              'governabilidade/user_packages.R'))

# Packages Utilizados 

packages <- c("tidyverse", 
              "ggtex",
              "ggside", 
              "lubridate",
              "RColorBrewer", 
              "scales")

# Instalando/Liberando 
library_packages(packages)
```

# Tema 4i - theme()

```{r}

thema = theme(legend.position = "bottom",
              ggside.panel.scale = 0.2,
        panel.background = element_rect(fill = "transparent"),
        #strip.text = element_text(face="bold", size=9),
        strip.background = element_rect(fill = "#f5f5f5"), 
                legend.background = element_blank(),
                axis.text.x = element_text(angle = 90, 
                                           hjust = 1, 
                                           size = 16),
                axis.text.y = element_text(size = 14), 
                strip.text.x = element_text(size = 14),
                strip.text.y = element_text(size = 17),
                axis.title.y = element_text(size = 11L),
                legend.text = element_text(color = "#0A2240", 
                                           size =  15),
                legend.key = element_rect(fill = "transparent",
                                      colour = "transparent"),
            legend.key.size = unit(0.1, 'cm'),
            legend.margin = margin(-0.2, unit = "cm"),
            rect = element_rect(fill = "transparent"),
            plot.title.position = "plot",
            plot.margin = ggplot2::margin(1,1,1,1, 
                                  unit = "lines"),
            plot.caption.position =  "plot",
            # plot.caption = element_markdown(color = "black",
            #                                 size = 12),
            plot.title = element_text(color = "black", 
                                      size = 18,
                                      face = 'bold',
                                      margin = ggplot2::margin(b = 6)),
            plot.subtitle = element_text(color = "#616060",
                                         size = 14, 
                                         margin = ggplot2::margin(b = 6)),
            panel.grid.major = element_line(color = "#e9e9e9"),
            panel.grid.minor = element_blank(),
            panel.grid.major.x = element_blank(),
            panel.grid  = element_blank(),
            axis.ticks = element_blank(),
            plot.background = element_rect(fill = "transparent", 
                                           colour = NA))+
  theme(strip.text.x = element_text(margin = margin(.1, 1, .1, 1, "cm")))

```



# Chamando a função 

```{r}
# Opinião Pública 

source(paste0(git_path,
              'governabilidade/fct_calc_opiniao_pub.R'))

```

# Limpeza

```{r}
# Importa e limpa base de dados

hist_raw <- readxl::read_excel(paste0(alt_path,
                        'governabilidade/input/',
                        'Governabilidade_dados.xlsx'),
                         sheet = 'OpiniaoPublica') %>% 
            janitor::clean_names() %>% 
            rename(bom = otimo_bom)



opiniao_raw <- readxl::read_excel(paste0(alt_path,
                         'governabilidade/input/',
                         'dataBase_opinioPublica.xlsx'),
                         sheet = 'Geral') %>% 
               janitor::clean_names()
```

# Chamando a função de Opinião Pública 

```{r}

indice_pop = calc_opiniao_pub(historico = hist_raw, 
                              base_amostra = opiniao_raw)
```

# Plote com intervalo - Descontinuado por ausência do tamanho da amostra 

```{r}

# ggplot2::ggplot(indice_pop, 
#        aes(y = bom, x = data)) +
#   geom_point() + 
#   geom_point(aes(y= avg_pond), 
#              color = '#EE771B') +
#   geom_line(aes(y= avg_pond),
#             color = '#EE771B', 
#             size = 1) +
#   geom_ribbon(aes(ymin=start, 
#                   ymax=end),
#                   alpha=0.2,
#                   fill = '#EE771B') +
#   geom_ribbon(aes(ymin=start_amostra,
#                   ymax=end_amostra),
#                   alpha=0.3, 
#                   fill = 'red') +
#   geom_vline(xintercept = as.numeric(indice_pop$data[c(1)]),
#              linetype = 2,
#              colour = "red")+
#   geom_label(label = "Dilma", size = 8.0,
#              x =  as.numeric(indice_pop$data[c(1)]), 
#              y = 1.0,
#              show.legend = F,
#              colour = "red") +
#   geom_vline(xintercept = as.numeric(indice_pop$data[c(20)]),
#              linetype = 2,
#              colour = "red")+
#   geom_label(label = "Temer", size = 8.0,
#              x =  as.numeric(indice_pop$data[c(20)]), 
#              y = 1.0,
#              show.legend = F,
#              colour = "red") +
#   geom_vline(xintercept = as.numeric(indice_pop$data[c(67)]),
#              linetype = 2,
#              colour = "red")+
#   geom_label(label = "Bolsonaro", size = 8.0,
#              x =  as.numeric(indice_pop$data[c(67)]), 
#              y = 1.0,
#              show.legend = F,
#              colour = "red") +
#   labs(y = "", x = "") +
#   ylim(0,1)+
#   theme(legend.position = "bottom", 
#         legend.text = element_text(size = 25),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 15),
#         axis.text.y = element_text(size = 15), 
#         strip.text.x = element_text(size = 15),
#         strip.text.y = element_text(size = 15),
#          axis.title.y = element_text(size = 20L),
#         axis.title.x = element_blank(), 
#         legend.title = element_blank())+
#   scale_y_continuous(labels = percent_format())
# 
# # Save Plot 
# 
# ggplot2::ggsave(
#   filename =  paste0(
#     alt_path,
#     "governabilidade/output/Plots/Opinao_Publica/v6",
#     "/plot01_opiniao.png"), 
#   width = 15, 
#   height = 7, 
#   dpi = 300, 
#   units = "in",
#   device='png') 

```

```{r}
# indice_pop <- readxl::read_excel("indice_popularidade.xlsx")
```


# Plot com média simples 

```{r}

depara_gov <- readxl::read_excel(paste0(alt_path, 
                           'governabilidade/output/Data/',
                           'indice_judiciario.xlsx')) %>% 
  select(date, gov) %>% 
  rename(index = gov) %>% 
  mutate(index = str_replace_all(index, " I", ""),
         index = str_replace_all(index, "I", ""))

hist = hist_raw %>% 
  dplyr::mutate(data = lubridate::floor_date(data,'month')) %>% 
  rename(date = data) %>% 
  right_join(depara_gov) %>% 
  relocate(index, .before = 'presidente') %>% 
  arrange(date) 
  
### 

volume_institutos <- hist %>% 
        select(date, instituto) %>% 
        stats::na.omit() %>% 
        group_by(date) %>% 
        summarise(numero_institutos = n(),
        institutos_distintos = n_distinct(instituto))

### 

mean_month = hist %>% 
  group_by(date, index) %>% 
  summarise(media_bom = mean(bom, na.rm = T), 
            media_regular = mean(regular, na.rm=T),
            date = date) %>% 
  ungroup() %>% 
  distinct(.keep_all = T) %>% 
  mutate(media_bom = ifelse(is.nan(media_bom), NA, media_bom),
         media_regular = ifelse(is.nan(media_regular), NA, media_regular)) %>% 
  group_by(index) %>% 
  mutate(
    media_bom = zoo::na.approx(media_bom, na.rm = F),
    media_regular = zoo::na.approx(media_regular, na.rm = F)) %>% 
  fill(media_bom) %>%
  fill(media_regular) %>% 
  ungroup() %>% 
  mutate(media_bom = media_bom/100,
         media_regular = media_regular/100,
         indice_pop = (media_bom + media_regular/2),
         date = as.Date(date),
         index = factor(index, 
                        levels = c('Lula', 'Dilma', 'Temer', 'Bolsonaro', 'Lula III'))) #%>% 
  #select(c(date, index, starts_with('indice_pop'))) 


 mean_month = full_join(mean_month, 
                        volume_institutos, 
                        by = "date") %>% 
              dplyr::filter(date > "2002-12-01")


writexl::write_xlsx(mean_month,
                    paste0(
                      alt_path,
                      '/governabilidade/output/Data/',
                      'new_indice_popularidade.xlsx'))

############# Atualiza aqui ===============================

indice_pop_dantas <- readxl::read_excel(paste0(alt_path,
                                               'governabilidade/output/Data/historico/2024/marco_2024/',
                                               'indice_pop.xlsx')) %>% 
  mutate(date = as.Date(date),
         index = ifelse(date >= "2023-01-01", "Lula III", index), 
         index = factor(index, 
                        levels = c('Lula', 'Dilma', 'Temer', 'Bolsonaro', 'Lula III'))) 



ggplot2::ggplot(indice_pop_dantas) +
  aes(x = date, y = indice_pop) +
  geom_line(size = 1.0) +
  facet_grid(~index,  scale = 'free_x', space="free_x")+
  labs(y = "", x = "")+
    ylim(0,1)+
    scale_y_continuous(labels = percent_format(), 
                       limits = c(0,1))+
    scale_x_date(date_labels = "%Y-%m",
                 date_breaks = '1 year',
                 date_minor_breaks = '3 month',
                 expand = c(0.05,1))+thema
  
ggplot2::ggsave(filename =  paste0(
    alt_path,
    "governabilidade/output/Plots/",
    "/plot_popularidade.png"),
       width = 15,
       height = 7,
       dpi = 300, 
       units = "in",
       device='png') 


##########################################################

plot_mean = hist_raw %>% 
            dplyr::mutate(month = substr(data, 1,7)) %>% 
            relocate(month, .after = data) %>% 
            rename(date = data) %>% 
            mutate(index = case_when(date >= '2003-01-01' &
                               date <= '2010-12-01' ~ 'Lula',
                               date >= '2011-01-01' &
                                     date <= '2016-09-01' ~ 'Dilma', 
                               date >= '2016-09-01' &
                                  date < '2019-01-01' ~ 'Temer',
                            date >= '2019-01-01' ~ 'Bolsonaro')) %>% 
          relocate(index, .after = month) 


mean_month = plot_mean %>% 
             group_by(month, index) %>% 
             summarise(media_bom = mean(bom), 
                       numero_institutos = n(),
                       institutos_distintos = n_distinct(instituto)) %>% 
              ungroup() %>% distinct(month, .keep_all = T)

# writexl::write_xlsx(mean_month, "dados_popularidade.xlsx")

mean_month = plot_mean %>% 
          group_by(month, index) %>% 
          summarise(media_bom = mean(bom), 
                    date = date) 

ggplot2::ggplot(grafico) +
       aes(x = date, y = media_bom) +
       geom_line(colour = paleta$azul_4i) +
  ylim(0,100)+
  labs(y = "%", x = "")+
  theme_gray()+
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15), 
        axis.title.y = element_text(size = 15))+
  geom_vline(xintercept = as.numeric(mean_month$date[c(1)]),
             linetype = 2,
             colour = paleta$laranja_4i)+
  geom_label(label = "Lula", size = 7.0,
             x =  as.numeric(mean_month$date[c(1)]), 
             y = 100,
             show.legend = F,
             colour = paleta$laranja_4i) +
  geom_vline(xintercept = as.numeric(mean_month$date[c(66)]),
             linetype = 2,
             colour = paleta$laranja_4i)+
  geom_label(label = "Dilma", size = 7.0,
             x =  as.numeric(mean_month$date[c(66)]), 
             y = 100,
             show.legend = F,
             colour = paleta$laranja_4i) +
  geom_vline(xintercept = as.numeric(mean_month$date[c(162)]),
             linetype = 2,
             colour = paleta$laranja_4i)+
  geom_label(label = "Temer", size = 7.0,
             x =  as.numeric(mean_month$date[c(162)]), 
             y = 100,
             show.legend = F,
             colour = paleta$laranja_4i) +
  geom_vline(xintercept = as.numeric(mean_month$date[c(211)]),
             linetype = 2,
             colour = paleta$laranja_4i)+
  geom_label(label = "Bolsonaro", size = 7.0,
             x =  as.numeric(mean_month$date[c(211)]), 
             y = 100,
             show.legend = F,
             colour = paleta$laranja_4i)


# Save Plot 

ggplot2::ggsave(
  filename =  paste0(
    alt_path,
    "governabilidade/output/Plots/Opinao_Publica/v6",
    "/plot02_opiniao.png"), 
  width = 15, 
  height = 7, 
  dpi = 300, 
  units = "in",
  device='png') 
```

